http:
  listener:
    host: "localhost"
    port: "8081"
    path: "/travelOnTripCall/{serviceType}"

db:
  mysql:
    host: "localhost"
    port: "3306"
    username: "root"
    password: "Shekar@492"
    database: "busservices"